[versions]
agp = "8.13.2"
appcompat = "1.7.1"
activity = "1.12.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
